# Generated by Django 4.1 on 2023-11-20 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=30)),
                ('birthday_year', models.DateField(max_length=4)),
                ('birthday_month', models.DateField(max_length=2)),
                ('birthday_date', models.DateField(max_length=2)),
                ('gender', models.CharField(max_length=5)),
                ('check_email', models.EmailField(max_length=30)),
                ('mobile', models.CharField(default='01000000000', max_length=11)),
            ],
            options={
                'db_table': 'my_user',
            },
        ),
    ]
