# Generated by Django 4.1 on 2023-11-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='birthday_date',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='birthday_month',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='birthday_year',
            field=models.CharField(max_length=4),
        ),
    ]
