# Generated by Django 4.1 on 2023-11-29 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday_date',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday_month',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday_year',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='car',
            field=models.JSONField(default=dict, null=True, verbose_name='json'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(default='01000000000', max_length=12, null=True),
        ),
    ]
