# Generated by Django 4.1 on 2023-11-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_usermodel_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='mobile',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
